/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pointofsale;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author shah
 */
public class FrontPage extends javax.swing.JFrame {

    /**
     * Creates new form FrontPage
     */
    public FrontPage() {
        initComponents();
//        setVisible(true);
//        setSize(600, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtfldUsername = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        lblLogIn = new javax.swing.JLabel();
        BtnLogIn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Point Of Sale");
        setMinimumSize(new java.awt.Dimension(770, 440));
        setName("Point Of Sale"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(770, 440));
        getContentPane().setLayout(null);

        lblUserName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(255, 255, 255));
        lblUserName.setText("Username");
        getContentPane().add(lblUserName);
        lblUserName.setBounds(190, 230, 80, 30);

        lblPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password");
        getContentPane().add(lblPassword);
        lblPassword.setBounds(190, 260, 110, 60);

        txtfldUsername.setToolTipText("Enter username");
        txtfldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtfldUsername);
        txtfldUsername.setBounds(320, 230, 120, 30);

        passField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFieldActionPerformed(evt);
            }
        });
        getContentPane().add(passField);
        passField.setBounds(320, 280, 120, 30);

        lblLogIn.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblLogIn.setForeground(new java.awt.Color(255, 255, 255));
        lblLogIn.setText("Log In");
        getContentPane().add(lblLogIn);
        lblLogIn.setBounds(290, 80, 190, 90);

        BtnLogIn.setText("Log In");
        BtnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogInActionPerformed(evt);
            }
        });
        getContentPane().add(BtnLogIn);
        BtnLogIn.setBounds(440, 350, 140, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pointofsale/POS-Image-block.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 820, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldUsernameActionPerformed
        String username=txtfldUsername.getText();
    }//GEN-LAST:event_txtfldUsernameActionPerformed

    private void passFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFieldActionPerformed
        int password=Integer.parseInt(passField.getText());
    }//GEN-LAST:event_passFieldActionPerformed

    private void BtnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogInActionPerformed
        String username=txtfldUsername.getText();
        String password=passField.getText();
        ArrayList<String> passwordArray=new ArrayList<>();
        String file="D:\\java\\PointOfSale\\src\\pointofsale\\password.txt";
        BufferedReader br = null;
        boolean state=false;
        
        try {
            br = new BufferedReader(new FileReader(file));
        } 
        catch (FileNotFoundException ex) {
            Logger.getLogger(FrontPage.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
        String line;
        
        try {
            while((line=br.readLine())!=null){
                passwordArray.add(line);
            }
        }
        catch (IOException ex) {
            Logger.getLogger(FrontPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(passwordArray.get(0));
        System.out.println(passwordArray.get(1));
        for(int i=0;i<passwordArray.size();){
           if(passwordArray.get(i++).equals(username)&&passwordArray.get(i++).equals(password)){
               SecondPage secondpage=new SecondPage();
        secondpage.setVisible(true);
        secondpage.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
           }
           else
           {
               System.out.println("wrong password");
               break;
           }
        }
        
        
    }//GEN-LAST:event_BtnLogInActionPerformed

  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrontPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogIn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblLogIn;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPasswordField passField;
    private javax.swing.JTextField txtfldUsername;
    // End of variables declaration//GEN-END:variables
}
